"""initial schema

Revision ID: 8cc49a1817eb
Revises:
Create Date: 2026-09-25 13:28:07.210506

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cc49a1817eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("caller_id", sa.String(length=256), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "connectors",
        sa.Column("connector_id", sa.String(length=128), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("mapping_version", sa.String(length=32), nullable=False),
        sa.Column("health", sa.String(length=24), nullable=False),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_observation", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("connector_id"),
    )
    op.create_table(
        "detection_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("findings_created", sa.Integer(), nullable=False),
        sa.Column("findings_updated", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "findings",
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("detection_id", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.String(length=24), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=True),
        sa.Column("device_id", sa.String(length=256), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("destination", sa.String(length=1024), nullable=True),
        sa.Column("mcp_server_id", sa.String(length=256), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index("ix_finding_last_id", "findings", ["last_seen", "finding_id"], unique=False)
    op.create_index(op.f("ix_findings_destination"), "findings", ["destination"], unique=False)
    op.create_index(op.f("ix_findings_detection_id"), "findings", ["detection_id"], unique=False)
    op.create_index(op.f("ix_findings_device_id"), "findings", ["device_id"], unique=False)
    op.create_index(op.f("ix_findings_first_seen"), "findings", ["first_seen"], unique=False)
    op.create_index(op.f("ix_findings_last_seen"), "findings", ["last_seen"], unique=False)
    op.create_index(op.f("ix_findings_mcp_server_id"), "findings", ["mcp_server_id"], unique=False)
    op.create_index(op.f("ix_findings_provider"), "findings", ["provider"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_index(op.f("ix_findings_user_id"), "findings", ["user_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.Column("connector_id", sa.String(length=128), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_event_id", sa.String(length=256), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=True),
        sa.Column("device_id", sa.String(length=256), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("destination_domain", sa.String(length=256), nullable=True),
        sa.Column("mcp_server_id", sa.String(length=256), nullable=True),
        sa.Column("correlation_id", sa.String(length=256), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    op.create_index(
        "ix_observation_connector_event",
        "observations",
        ["connector_id", "source_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observations_connector_id"), "observations", ["connector_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_correlation_id"), "observations", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_destination_domain"),
        "observations",
        ["destination_domain"],
        unique=False,
    )
    op.create_index(op.f("ix_observations_device_id"), "observations", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_observations_mcp_server_id"), "observations", ["mcp_server_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_observed_at"), "observations", ["observed_at"], unique=False
    )
    op.create_index(op.f("ix_observations_provider"), "observations", ["provider"], unique=False)
    op.create_index(op.f("ix_observations_user_id"), "observations", ["user_id"], unique=False)
    op.create_table(
        "registry_assets",
        sa.Column("asset_id", sa.String(length=256), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("canonical_endpoint", sa.String(length=1024), nullable=False),
        sa.Column("endpoint_domain", sa.String(length=256), nullable=True),
        sa.Column("approval_status", sa.String(length=32), nullable=False),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_registry_assets_asset_type"), "registry_assets", ["asset_type"], unique=False
    )
    op.create_index(
        op.f("ix_registry_assets_canonical_endpoint"),
        "registry_assets",
        ["canonical_endpoint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registry_assets_endpoint_domain"),
        "registry_assets",
        ["endpoint_domain"],
        unique=False,
    )
    op.create_index(op.f("ix_registry_assets_name"), "registry_assets", ["name"], unique=False)
    op.create_table(
        "connector_sync_state",
        sa.Column("connector_id", sa.String(length=128), nullable=False),
        sa.Column("cursor", sa.String(length=1024), nullable=True),
        sa.Column("checkpoint_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.connector_id"],
        ),
        sa.PrimaryKeyConstraint("connector_id"),
    )
    op.create_table(
        "finding_evidence",
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_reference", sa.String(length=1024), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.finding_id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.observation_id"],
        ),
        sa.PrimaryKeyConstraint("finding_id", "observation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_evidence")
    op.drop_table("connector_sync_state")
    op.drop_index(op.f("ix_registry_assets_name"), table_name="registry_assets")
    op.drop_index(op.f("ix_registry_assets_endpoint_domain"), table_name="registry_assets")
    op.drop_index(op.f("ix_registry_assets_canonical_endpoint"), table_name="registry_assets")
    op.drop_index(op.f("ix_registry_assets_asset_type"), table_name="registry_assets")
    op.drop_table("registry_assets")
    op.drop_index(op.f("ix_observations_user_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_provider"), table_name="observations")
    op.drop_index(op.f("ix_observations_observed_at"), table_name="observations")
    op.drop_index(op.f("ix_observations_mcp_server_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_device_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_destination_domain"), table_name="observations")
    op.drop_index(op.f("ix_observations_correlation_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_connector_id"), table_name="observations")
    op.drop_index("ix_observation_connector_event", table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_findings_user_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_provider"), table_name="findings")
    op.drop_index(op.f("ix_findings_mcp_server_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_last_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_first_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_device_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_detection_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_destination"), table_name="findings")
    op.drop_index("ix_finding_last_id", table_name="findings")
    op.drop_table("findings")
    op.drop_table("detection_runs")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
